repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version
    rev: v0.14.10
    hooks:
      # 1. Run the linter and fix what is possible automatically
      - id: ruff
        args: [ --fix ]
      # 2. Run the formatter to ensure consistent spacing/quotes
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        # This tells it to use the config in the root pyproject.toml
        additional_dependencies:
          - tomli