import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '../../../../../../'))
import logging
from google.adk.tools import ToolContext


def get_copyinto_query_from_memory(object_identifier: str, tool_context: ToolContext) -> dict:
    """
    Retrieve the pre-generated COPY INTO query for a specific table from the session state.

    This tool reads app:TASKS_PERFORMED from the session state to look up the COPY INTO
    query previously generated by the Copy Into Specialist (with ONE_TIME_LOAD=FALSE)
    for a given table. It filters entries by OBJECT_TYPE=CopyInto, OPERATION_STATUS=SUCCESS,
    OPERATION_TYPE=COPY INTO QUERY GENERATED, and OBJECT_IDENTIFIER matching the provided value.

    Args:
        object_identifier: The fully-qualified table identifier used when the query was
                           generated, e.g. "DATABASE.SCHEMA.TABLE".
        tool_context: ADK tool context containing state information.

    Returns:
        Dictionary with the matching session state entries for the given object_identifier.
    """
    try:
        logger_name = tool_context.state.get("app:LOGGER")
        logger = logging.getLogger(logger_name).getChild(__name__)
        logger.info("Inside function: get_copyinto_query_from_memory, object_identifier=%s", object_identifier)

        tasks = tool_context.state.get("app:TASKS_PERFORMED", [])
        results = [
            t for t in tasks
            if isinstance(t, dict)
            and t.get("OBJECT_TYPE") == "CopyInto"
            and t.get("OPERATION_STATUS") == "SUCCESS"
            and t.get("OPERATION_TYPE") == "COPY INTO QUERY GENERATED"
            and t.get("OBJECT_IDENTIFIER") == object_identifier
        ]
        logger.info(
            "get_copyinto_query_from_memory returned %d entries for object_identifier=%s",
            len(results), object_identifier
        )
        return {"results": results, "object_identifier": object_identifier}
    except Exception as e:
        logger_name = tool_context.state.get("app:LOGGER")
        logger = logging.getLogger(logger_name).getChild(__name__)
        logger.error(
            "Error retrieving copy-into query from memory for %s: %s",
            object_identifier, str(e)
        )
        return {
            "success": False,
            "results": [],
            "object_identifier": object_identifier,
            "error": str(e),
            "message": f"Error retrieving COPY INTO query for '{object_identifier}' from memory: {str(e)}"
        }
