#!/usr/bin/env python3
"""Cloud Function: Real-time Vector Search 2.0 sync for product changes.

Triggered by Cloud Pub/Sub on product_created, product_updated, and
product_deleted events. Upserts or deletes product data objects in
the Vector Search 2.0 Collection. Embeddings are auto-generated by
the Collection's configured embedding model.

Deploy:
    gcloud functions deploy pubsub-sync \
        --gen2 \
        --runtime python311 \
        --trigger-topic product-changes \
        --entry-point handle_product_event \
        --region us-central1 \
        --project YOUR_PROJECT_ID

Environment variables:
    GOOGLE_CLOUD_PROJECT: GCP project ID
    GOOGLE_CLOUD_LOCATION: GCP region (default: us-central1)
    VECTOR_SEARCH_COLLECTION: Vector Search 2.0 collection resource name
    DELETION_MODE: "hard" or "soft" (default: hard)
"""

import base64
import json
import logging
import os

import functions_framework
from google.cloud import bigquery, vectorsearch

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

PROJECT_ID = os.getenv("GOOGLE_CLOUD_PROJECT", "")
LOCATION = os.getenv("GOOGLE_CLOUD_LOCATION", "us-central1")
COLLECTION = os.getenv("VECTOR_SEARCH_COLLECTION", "")
DELETION_MODE = os.getenv("DELETION_MODE", "hard")


def fetch_product(product_id: str) -> dict | None:
    """Fetch product from BigQuery by ID."""
    client = bigquery.Client(project=PROJECT_ID)
    query = f"""
        SELECT * FROM `{PROJECT_ID}.retail_skill_products.products`
        WHERE product_id = @product_id
        LIMIT 1
    """
    config = bigquery.QueryJobConfig(
        query_parameters=[bigquery.ScalarQueryParameter("product_id", "STRING", product_id)]
    )
    for row in client.query(query, job_config=config).result():
        return dict(row.items())
    return None


def upsert_to_vector_search(product_id: str, product_data: dict) -> None:
    """Upsert a product data object to Vector Search 2.0 Collection.

    Embeddings are auto-generated by the Collection's configured model.
    """
    client = vectorsearch.DataObjectServiceClient()
    data_object = vectorsearch.DataObject(data_object_id=product_id, data=product_data)
    request = vectorsearch.UpsertDataObjectRequest(parent=COLLECTION, data_object=data_object)
    client.upsert_data_object(request)
    logger.info(f"Upserted product {product_id}")


def delete_from_vector_search(product_id: str) -> None:
    """Delete or soft-delete a product from Vector Search 2.0."""
    if DELETION_MODE == "hard":
        client = vectorsearch.DataObjectServiceClient()
        request = vectorsearch.DeleteDataObjectRequest(parent=COLLECTION, data_object_id=product_id)
        client.delete_data_object(request)
        logger.info(f"Deleted product {product_id}")
    else:
        product = fetch_product(product_id)
        if product:
            product["stock"] = 0
            metadata = {
                "product_id": product_id,
                "name": product.get("name", ""),
                "price": product.get("price", 0.0),
                "category": product.get("category", ""),
                "brand": product.get("brand", ""),
            }
            upsert_to_vector_search(product_id, metadata)
            logger.info(f"Soft-deleted (marked out-of-stock) product {product_id}")


@functions_framework.cloud_event
def handle_product_event(cloud_event):
    """Handle product change events from Pub/Sub.

    Expected message: {"action": "created"|"updated"|"deleted", "product_id": "prod-001"}
    """
    data = base64.b64decode(cloud_event.data["message"]["data"]).decode("utf-8")
    message = json.loads(data)

    action = message.get("action", "")
    product_id = message.get("product_id", "")

    if not product_id:
        logger.error("No product_id in message")
        return

    logger.info(f"Processing {action} for product {product_id}")

    if action == "deleted":
        delete_from_vector_search(product_id)
        return

    product = fetch_product(product_id)
    if not product:
        logger.error(f"Product {product_id} not found in BigQuery")
        return

    product_data = {
        "product_id": product_id,
        "name": product.get("name", ""),
        "price": product.get("price", 0.0),
        "description": product.get("description", ""),
        "category": product.get("category", ""),
        "brand": product.get("brand", ""),
    }

    upsert_to_vector_search(product_id, product_data)
    logger.info(f"Successfully processed {action} for product {product_id}")
