from .informationschema import InformationSchema
class ColumnColumnList:
    _view=InformationSchema._column_view
    _table_catalog="TABLE_CATALOG"
    _table_schema="TABLE_SCHEMA"
    _table_name="TABLE_NAME"
    _column_name="COLUMN_NAME"
    _ordinal_position="ORDINAL_POSITION"
    _column_default="COLUMN_DEFAULT"
    _is_nullable="IS_NULLABLE"
    _data_type="DATA_TYPE"
    _character_maximum_length="CHARACTER_MAXIMUM_LENGTH"
    _character_octet_length="CHARACTER_OCTET_LENGTH"
    _numeric_precision="NUMERIC_PRECISION"
    _numeric_precision_radix="NUMERIC_PRECISION_RADIX"
    _numeric_scale="NUMERIC_SCALE"
    _datetime_precision="DATETIME_PRECISION"
    _interval_type="INTERVAL_TYPE"
    _interval_precision="INTERVAL_PRECISION"
    _character_set_catalog="CHARACTER_SET_CATALOG"
    _character_set_schema="CHARACTER_SET_SCHEMA"
    _character_set_name="CHARACTER_SET_NAME"
    _collation_catalog="COLLATION_CATALOG"
    _collation_schema="COLLATION_SCHEMA"
    _collation_name="COLLATION_NAME"
    _domain_catalog="DOMAIN_CATALOG"
    _domain_schema="DOMAIN_SCHEMA"
    _domain_name="DOMAIN_NAME"
    _udt_catalog="UDT_CATALOG"
    _udt_schema="UDT_SCHEMA"
    _udt_name="UDT_NAME"
    _scope_catalog="SCOPE_CATALOG"
    _scope_schema="SCOPE_SCHEMA"
    _scope_name="SCOPE_NAME"
    _maximum_cardinality="MAXIMUM_CARDINALITY"
    _dtd_identifier="DTD_IDENTIFIER"
    _is_self_referencing="IS_SELF_REFERENCING"
    _is_identity="IS_IDENTITY"
    _identity_generation="IDENTITY_GENERATION"
    _identity_start="IDENTITY_START"
    _identity_increment="IDENTITY_INCREMENT"
    _identity_maximum="IDENTITY_MAXIMUM"
    _identity_minimum="IDENTITY_MINIMUM"
    _identity_cycle="IDENTITY_CYCLE"
    _identity_ordered="IDENTITY_ORDERED"
    _schema_evolution_record="SCHEMA_EVOLUTION_RECORD"
    _comment="COMMENT"
    _data_type_alias="DATA_TYPE_ALIAS"

class InformationSchemaColumn:
    def __init__(self):
        self.columns=ColumnColumnList()