# SECTION - 1
# Please update as needed.
# Please use Single Quotes for values that are strings with spaces
# Multiline values are not supported.
GOOGLE_GENAI_USE_VERTEXAI=0
GOOGLE_API_KEY=NOT_SET
MCP_AUDIENCE=NOT_SET
LOGGING_LEVEL=info
GEMINI_MODEL=gemini-2.5-flash
# Make sure that AGENT_NAME is without spaces, separate with underscores
AGENT_NAME=weather_agent
AGENT_DESCRIPTION='A helpful assistant for user questions.'
AGENT_PROMPT='Answer user questions to the best of your knowledge'
MCP_TOOLSET_NAME=MCP_TOOLSET
# required only for the local run when the MCP is IAM authenticated
# sample value 
# GOOGLE_APPLICATION_CREDENTIALS = cloud-run-invoker-sa.json
GOOGLE_APPLICATION_CREDENTIALS=NOT_SET


# SECTION - 2, Agent Deployment
PROJECT_ID=NOT_SET
REGION=us-central1
# Agent Engine Specific - Should be using format - gs://your-agent-engine-staging-bucket
AGENT_ENGINE_STAGING_BUCKET=NOT_SET


# SECTION - 3, Agentspace registration
# Agentspace Specific
PROJECT_NUMBER=NOT_SET
AGENT_LOCATION=us-central1
REASONING_ENGINE_NUMBER=NOT_SET
AGENT_SPACE_APP_NAME=NOT_SET
DISPLY_NAME_IN_AGENTSPACE_APP=NOT_SET
DESCRIPTION_IN_AGENTSPACE_APP=NOT_SET
TOOL_DESCRIPTION_IN_AGENTSPACE_APP=NOT_SET

# Other variables
# default -1 means send all user conversations to the LLM
# recommended value - 5. Please check the documentation for more.
MAX_PREV_USER_INTERACTIONS=-1

# Refresh Token before this threashold.
# Generally does not need changing.
TOKEN_REFRESH_THRESHOLD_MINS=15