# This file contains the configuration required to enable click-to-deploy for Agent Packs.
# - The "template" field should not be modified as it indicates which template was used to build this agent.
# - The "config_yaml_jinja_template" and "params.*" fields may be updated to control what user-configurable arguments may be provided for deployment.
# - The "envs.*" fields may be added or updated to store pre-configured environments. Required environments are: "staging" and "prod".

template = "adk"
catalog_id = '3e344686-88c7-4b17-98d2-bad6bc5fdfa7'
config_yaml_jinja_template = """
agent_name: "nurse-handover"
agent_project: "{{ project_id }}"
agent_region: "{{ agent_region }}"
enable_iap: {{ enable_iap }}
state_bucket: "{{ state_bucket }}"
vars:
  GOOGLE_CLOUD_PROJECT: "{{ project_id }}"
  GOOGLE_CLOUD_LOCATION: "global"
  GOOGLE_GENAI_USE_VERTEXAI: "true"
  AGENT_MODEL_NAME: "gemini-2.5-flash"
  SECTION_MODEL_NAME: "gemini-2.5-pro"
  SUMMARY_MODEL_NAME: "gemini-2.5-flash"
"""

[params.project_id]
default = "gcp-project-id"
description = "GCP project ID to use for deployment."

[params.state_bucket]
default = "{{ project_id }}-nurse-handover-tfstate"
description = "GCS bucket name to use for storing terraform state."

[params.agent_region]
default = "us-central1"
description = "GCP location for hosting the agent."

[params.enable_iap]
default = false
description = "Whether to enable IAP on the deployed agent service."

[envs.staging]
project_id = "agent-catalog-staging-0"
state_bucket = "agent-catalog-staging-0-nurse-handover-tfstate"
enable_iap = true

[envs.prod]
project_id = "agent-catalog-demo-1"
state_bucket = "agent-catalog-demo-1-nurse-handover-tfstate"
enable_iap = true
