# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Standard imports
import json
import os
import time
import pandas as pd
import logging

# Google/ADK imports
import vertexai
from google.cloud import storage
from vertexai.evaluation import EvalTask, PointwiseMetric
from vertexai.generative_models import GenerativeModel

# import configuration
from ...config import config

# Logging Setup
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)


# Utility: upload to GCS
# TODO: make this tool common across all agents
def _upload_to_gcs(local_path: str, bucket_name: str, folder_name: str) -> str:
    """Uploads a local file to a specific folder in Google Cloud Storage."""
    logger.info(
        f"Uploading file {local_path} to GCS bucket {bucket_name} in folder {folder_name}..."
    )
    storage_client = storage.Client()
    bucket = storage_client.bucket(bucket_name)
    blob_name = f"{folder_name}/{os.path.basename(local_path)}"
    blob = bucket.blob(blob_name)
    blob.upload_from_filename(local_path)
    gcs_path = f"gs://{bucket_name}/{blob_name}"
    logger.info(f"Successfully uploaded file to {gcs_path}")
    return gcs_path


# MAIN Utility: Evaluate fine tuned model
def evaluate_model(
    model_endpoint: str,
) -> str:
    """Evaluates a fine-tuned Text-to-SQL model using the Vertex AI Evaluation service."""
    # set configurations
    project_id = config.project_id
    location = config.location
    eval_dataset_path = config.eval_dataset
    gcs_bucket_name = config.bucket_name

    logger.info(f"--- Executing Tool: evaluate_model ---")
    logger.info(
        f"Received parameters: model_endpoint={model_endpoint}, eval_dataset_path={eval_dataset_path}, project_id={project_id}, location={location}, gcs_bucket_name={gcs_bucket_name}"
    )
    vertexai.init(project=project_id, location=location)

    # Resolve seed_data_path for local files if it's not a GCS path
    if not eval_dataset_path.startswith("gs://"):
        # If the path is relative, resolve it relative to the current script's directory
        if not os.path.isabs(eval_dataset_path):
            # Get the absolute path of the current script's directory
            current_script_dir = os.path.dirname(os.path.abspath(__file__))
            eval_dataset_path = os.path.join(
                current_script_dir, eval_dataset_path
            )
        logger.info(f"Resolved local eval_dataset_path: {eval_dataset_path}")

    # Load the evaluation dataset
    eval_df = pd.read_csv(eval_dataset_path)
    tuned_model = GenerativeModel(model_endpoint)

    # Generate predictions
    logger.info("Generating predictions from the fine-tuned model...")
    predictions = [
        tuned_model.generate_content(
            f"Question: {row['question']}\n\nSQL:"
        ).text.strip()
        for _, row in eval_df.iterrows()
    ]
    eval_df["response"] = predictions
    logger.info("Successfully generated predictions.")
    logger.info(f"Sample predictions:\n{eval_df.head()}\n")

    # Rename columns to match the expected format for the evaluation task
    # We map 'ground_truth_sql' to 'context' so it is available to the evaluator prompt
    eval_df = eval_df.rename(
        columns={"question": "instruction", "ground_truth_sql": "context"}
    )

    # Define the evaluation task with a domain-specific SQL Metric
    logger.info("Defining the evaluation task...")

    sql_accuracy_prompt = """You are a Senior Data Engineer evaluating the quality of SQL queries generated by an AI model. 
Your goal is to determine if the GENERATED SQL is functionally equivalent to the GROUND TRUTH SQL.

# Evaluation Criteria
1. **Functional Correctness**: Does the generated SQL retrieve exactly the same data as the ground truth? (e.g., same filters, joins, aggregations).
2. **Schema Adherence**: Does the generated SQL use columns and tables that appear to be valid based on the ground truth context?
3. **Syntax**: Is the SQL syntactically valid standard SQL?

# Rating Rubric
5 (Correct): The generated SQL is semantically equivalent to the Ground Truth. (Note: different aliases or ordering of WHERE clauses is fine as long as the result is the same).
4 (Minor Error): The logic is correct, but there is a minor syntax issue or unnecessary column included that does not affect the core result.
3 (Logic Error): The SQL uses the wrong columns, wrong join type, or misses a specific filter condition required by the ground truth.
2 (Major Error): The SQL queries the wrong table or hallucinates columns entirely.
1 (Complete Failure): The response is not valid SQL or is irrelevant.

# Evaluation Steps
STEP 1: Compare the SELECT clauses. Are they retrieving the same fields?
STEP 2: Compare the JOINs and WHERE clauses. Is the filtering logic identical?
STEP 3: Compare GROUP BY and ORDER BY. Is the aggregation and sorting identical?
STEP 4: Ignore formatting differences (indentation, capitalization, alias names). Focus on the logic.

Give step by step explanations for your scoring, and only choose scores from 5, 4, 3, 2, 1.

# User Inputs
### QUESTION
{instruction}

### GROUND TRUTH SQL
{context}

### GENERATED SQL
{response}"""

    eval_task = EvalTask(
        dataset=eval_df,
        metrics=[
            PointwiseMetric(
                metric="sql_accuracy",
                metric_prompt_template=sql_accuracy_prompt,
            )
        ],
    )

    logger.info("Starting evaluation...")
    eval_result = eval_task.evaluate()
    logger.info("Evaluation completed.")

    results_filename = f"evaluation_results_{int(time.time())}.json"
    eval_result.metrics_table.to_json(
        results_filename, orient="records", lines=True
    )
    logger.info(f"Saved detailed evaluation results to {results_filename}")

    # Upload the results to GCS
    results_gcs_path = _upload_to_gcs(
        results_filename, gcs_bucket_name, "evaluation_results"
    )

    # Calculate average scores
    # Note: The metric name in the table will be 'sql_accuracy/score' based on the metric name defined above
    avg_sql_accuracy = eval_result.metrics_table["sql_accuracy/score"].mean()

    # Remove local temp files
    os.remove(results_filename)

    output = {
        "average_sql_accuracy": avg_sql_accuracy,
        "detailed_results_gcs_path": results_gcs_path,
    }
    logger.info(f"Returning from tool: {json.dumps(output)}")
    return json.dumps(output)
