class AccountUsage:
    def __init__(self):
        pass
    _account_usage = "SNOWFLAKE.ACCOUNT_USAGE"
    _query_history_view = f"{_account_usage}.QUERY_HISTORY"
    _login_history_view = f"{_account_usage}.LOGIN_HISTORY"
    _warehouse_metering_history_view = f"{_account_usage}.WAREHOUSE_METERING_HISTORY"
    _storage_usage_view = f"{_account_usage}.STORAGE_USAGE"
    _table_storage_metrics_view = f"{_account_usage}.TABLE_STORAGE_METRICS"
    _access_history_view = f"{_account_usage}.ACCESS_HISTORY"
    _copy_history_view = f"{_account_usage}.COPY_HISTORY"
    _task_history_view = f"{_account_usage}.TASK_HISTORY"
    _grants_to_roles_view = f"{_account_usage}.GRANTS_TO_ROLES"
    _users_view = f"{_account_usage}.USERS"
    _warehouse_events_history_view = f"{_account_usage}.WAREHOUSE_EVENTS_HISTORY"
    _sessions_view = f"{_account_usage}.SESSIONS"
    _roles_view = f"{_account_usage}.ROLES"
    _grants_to_users_view = f"{_account_usage}.GRANTS_TO_USERS"
    _metering_daily_history_view = f"{_account_usage}.METERING_DAILY_HISTORY"
    _data_transfer_history_view = f"{_account_usage}.DATA_TRANSFER_HISTORY"
    _automatic_clustering_history_view = f"{_account_usage}.AUTOMATIC_CLUSTERING_HISTORY"
    _materialized_view_refresh_history_view = f"{_account_usage}.MATERIALIZED_VIEW_REFRESH_HISTORY"
    _alert_history_view = f"{_account_usage}.ALERT_HISTORY"
    _load_history_view = f"{_account_usage}.LOAD_HISTORY"
    _stages_view = f"{_account_usage}.STAGES"
    _databases_view = f"{_account_usage}.DATABASES"
    _schemata_view = f"{_account_usage}.SCHEMATA"
    _pipes_view = f"{_account_usage}.PIPES"
    _serverless_task_history_view = f"{_account_usage}.SERVERLESS_TASK_HISTORY"
