#!/usr/bin/env python3
"""Ingest products into Vertex AI Vector Search 2.0 Collection.

Reads products from BigQuery, creates a Vector Search 2.0 Collection
(if it doesn't exist), and batch-inserts products as data objects.
Embeddings are auto-generated by the Collection's configured model.

Usage:
    python ingest_vertex_search.py \
        --project-id my-project \
        --collection-id my-products

    # Or use design-spec.md for defaults:
    python ingest_vertex_search.py --config design-spec.md
"""

import argparse
import logging
import sys
import time
from pathlib import Path

from typing import Dict, List

from google.api_core import exceptions
from google.cloud import bigquery, vectorsearch
from google.protobuf import struct_pb2

# Add _shared to path for shared utilities
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "_shared"))
from setup_utils import load_config

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

DEFAULT_EMBEDDING_MODEL = "gemini-embedding-001"
DEFAULT_EMBEDDING_FIELDS = ["name", "description", "category", "brand"]
BATCH_SIZE = 250  # VS 2.0 auto-embedding limit per batch

# All product fields stored as data object fields
PRODUCT_DATA_FIELDS = {
    "product_id": "string",
    "name": "string",
    "price": "number",
    "description": "string",
    "category": "string",
    "brand": "string",
    "image_url": "string",
    "rating": "number",
    "stock": "integer",
}


def fetch_products(project_id: str, dataset_id: str, table_id: str) -> List[Dict]:
    """Fetch products from BigQuery."""
    client = bigquery.Client(project=project_id)
    query = f"SELECT * FROM `{project_id}.{dataset_id}.{table_id}`"

    logger.info(f"Fetching products from {project_id}.{dataset_id}.{table_id}")
    results = client.query(query).result()
    products = [dict(row.items()) for row in results]
    logger.info(f"Fetched {len(products)} products")
    return products


def build_text_template(embedding_fields: List[str]) -> str:
    """Build the text_template for auto-embedding from field names.

    The template uses {field_name} placeholders that VS 2.0 resolves
    from the data object's data fields.
    """
    parts = [f"{field}: {{{field}}}" for field in embedding_fields]
    return " | ".join(parts)


def get_data_schema(products: List[Dict]) -> dict:
    """Build data schema from known product fields, only including
    fields that exist in the actual data."""
    properties = {}
    sample_keys = set()
    for p in products[:10]:
        sample_keys.update(p.keys())

    for field, field_type in PRODUCT_DATA_FIELDS.items():
        if field in sample_keys:
            properties[field] = {"type": field_type}

    return {"type": "object", "properties": properties}


def create_collection_if_needed(
    project_id: str,
    location: str,
    collection_id: str,
    embedding_model: str,
    embedding_fields: List[str],
    data_schema: dict,
) -> str:
    """Create a Vector Search 2.0 Collection if it doesn't exist.

    Returns the full collection resource path.
    """
    client = vectorsearch.VectorSearchServiceClient()
    parent = f"projects/{project_id}/locations/{location}"
    collection_name = f"{parent}/collections/{collection_id}"

    try:
        client.get_collection(
            request=vectorsearch.GetCollectionRequest(name=collection_name)
        )
        logger.info(f"Collection '{collection_id}' already exists")
        return collection_name
    except exceptions.NotFound:
        pass

    text_template = build_text_template(embedding_fields)
    logger.info(f"Creating collection '{collection_id}' with text_template: {text_template}")

    request = vectorsearch.CreateCollectionRequest(
        parent=parent,
        collection_id=collection_id,
        collection={
            "data_schema": data_schema,
            "vector_schema": {
                "text_embedding": {
                    "dense_vector": {
                        "dimensions": 768,
                        "vertex_embedding_config": {
                            "model_id": embedding_model,
                            "text_template": text_template,
                            "task_type": "RETRIEVAL_DOCUMENT",
                        },
                    },
                },
            },
        },
    )

    try:
        operation = client.create_collection(request=request)
        logger.info("Waiting for collection creation to complete...")
        operation.result()
        logger.info("Collection created successfully")
    except Exception as e:
        logger.error(f"Error creating collection: {e}")
        sys.exit(1)

    return collection_name


def ingest_products(
    collection_path: str,
    products: List[Dict],
) -> None:
    """Insert products into the Vector Search 2.0 Collection.

    Embeddings are auto-generated by the Collection's configured model.
    Uses individual inserts for reliability.
    """
    client = vectorsearch.DataObjectServiceClient()

    created = 0
    skipped = 0
    errors = 0

    for i, product in enumerate(products):
        product_id = str(product.get("product_id", ""))
        # Ensure ID is RFC1035 compliant (lowercase, starts with letter)
        safe_id = product_id.lower().replace("_", "-")
        if safe_id and not safe_id[0].isalpha():
            safe_id = "p-" + safe_id

        data_struct = struct_pb2.Struct()
        for field, field_type in PRODUCT_DATA_FIELDS.items():
            value = product.get(field)
            if value is None:
                continue
            # Preserve proper types for the schema
            if field_type == "number":
                data_struct.update({field: float(value)})
            elif field_type == "integer":
                data_struct.update({field: int(value)})
            else:
                data_struct.update({field: str(value)})

        try:
            client.create_data_object(
                parent=collection_path,
                data_object_id=safe_id,
                data_object=vectorsearch.DataObject(data=data_struct),
            )
            created += 1
        except exceptions.AlreadyExists:
            skipped += 1
        except Exception as e:
            errors += 1
            logger.warning(f"Failed to insert {safe_id}: {e}")

        if (i + 1) % 50 == 0 or (i + 1) == len(products):
            logger.info(f"Processed {i + 1}/{len(products)} products")

    logger.info(f"Ingestion complete: {created} created, {skipped} skipped, {errors} errors")



def main():
    parser = argparse.ArgumentParser(description="Ingest products to Vertex AI Vector Search 2.0")
    parser.add_argument("--config", default="", help="Path to design-spec.md (provides defaults for other args)")
    parser.add_argument("--project-id", help="GCP project ID")
    parser.add_argument("--location", default="us-central1", help="GCP region")
    parser.add_argument("--dataset-id", default="retail_skill_products", help="BigQuery dataset")
    parser.add_argument("--table-id", default="products", help="BigQuery table")
    parser.add_argument("--collection-id", default="retail-skill-products-collection", help="Vector Search 2.0 Collection ID")
    parser.add_argument("--embedding-model", default=DEFAULT_EMBEDDING_MODEL, help="Auto-embedding model (default: gemini-embedding-001)")
    parser.add_argument("--embedding-fields", default=",".join(DEFAULT_EMBEDDING_FIELDS), help="Comma-separated fields for embedding text template")

    args = parser.parse_args()

    # Load design-spec.md defaults — CLI args override config values
    if args.config:
        cfg = load_config(args.config)
        if not args.project_id:
            args.project_id = cfg.get("gcp_project_id", "")
        if args.location == "us-central1" and cfg.get("gcp_region"):
            args.location = cfg["gcp_region"]
        if cfg.get("collection_id") and args.collection_id == "retail-skill-products-collection":
            args.collection_id = cfg["collection_id"]
        if cfg.get("embedding_model"):
            model_name = cfg["embedding_model"].split(" ")[0]
            if args.embedding_model == DEFAULT_EMBEDDING_MODEL:
                args.embedding_model = model_name
        if cfg.get("embedding_fields") and args.embedding_fields == ",".join(DEFAULT_EMBEDDING_FIELDS):
            args.embedding_fields = cfg["embedding_fields"]

    if not args.project_id:
        parser.error("--project-id is required (or set gcp_project_id in design-spec.md)")

    embedding_fields = [f.strip() for f in args.embedding_fields.split(",")]

    # Fetch products from BigQuery
    products = fetch_products(args.project_id, args.dataset_id, args.table_id)
    if not products:
        logger.error("No products found in BigQuery")
        return

    # Create Collection if needed (with auto-embedding config)
    data_schema = get_data_schema(products)
    collection_path = create_collection_if_needed(
        args.project_id, args.location, args.collection_id,
        args.embedding_model, embedding_fields, data_schema,
    )

    # Ingest products — VS 2.0 auto-generates embeddings
    ingest_products(collection_path, products)

    logger.info(f"Successfully ingested {len(products)} products into collection '{args.collection_id}'")
    logger.info(f"Collection path: {collection_path}")
    logger.info("Set VECTOR_SEARCH_COLLECTION env var to this path in your agent.")


if __name__ == "__main__":
    main()
